Update footer.html
drawpile/drawpile.github.io pull request #3
Opened 2024-04-10 16:48 UTC by MorrowShore

A little update.

2024-04-10 17:27 UTC, askmeaboutlo0m requested changes
Even if the factual and technical mistakes are corrected, I don't think these changes really make sense. The only thing left would be the logo, which in this state is too large and distracting.

Also, on short pages, you're attacked by two identical logos from the top and bottom really close to each other, which looks weird. Better would be a monochrome version of the logo or a mascot picture instead to avoid this strange effect.

2024-04-10 17:27 UTC, askmeaboutlo0m commented on _includes/footer.html
> +        <p>© 2014-2024 Drawpile Project. All rights reserved.</p>
"Drawpile Project" is not a copyright holder. "All rights reserved" is outright contradictory to the site being licensed under CC-SA 4.0.

2024-04-10 17:27 UTC, askmeaboutlo0m commented on _includes/footer.html
>          <a href="https://discord.gg/M3yyMpC" target="_blank"><span class="icon"><span class="fab fa-discord"></span></span> Discord</a><br>
Not related to your change, but this should actually link to `https://drawpile.net/discord/`. Currently, this just forwards to the link here, but it's there in case we need to change it for some reason.

2024-04-10 17:27 UTC, askmeaboutlo0m commented on _includes/footer.html
> +        <img src="https://avatars.githubusercontent.com/u/25749259?s=150&amp;v=4" alt="Drawpile Logo"><br>
Don't hotlink a GitHub implementation detail. If anything, put the logo into `assets/img` instead.

Something about this also breaks the responsiveness, not sure if it's the logo or the centered text. If you narrow the page, it wonks out at one point and you get weird line breaks.

![image](https://github.com/drawpile/drawpile.github.io/assets/13625824/37cbe9b3-6aba-44ba-9fd4-8fb8748010e0)

2024-04-10 17:27 UTC, askmeaboutlo0m commented on _includes/footer.html
> +        <p>Drawpile is a Free &amp; Open-Source solution licensed mostly under <a href="https://www.gnu.org/licenses/quick-guide-gplv3.html">GPLv3</a>.</p>
Drawpile is not a solution.

Licensing information about the software belongs with the software, not in the footer of the website. Putting "mostly" in there also sounds incredibly suspicious, like it's some kind of open core model pretending to be open source.

2024-04-10 17:27 UTC, askmeaboutlo0m commented on _includes/footer.html
> +      <div class="column" style="text-align: center;">
Use `has-text-centered` from Bulma to center text, not a `style` tag.

2024-04-10 17:27 UTC, askmeaboutlo0m commented on _includes/footer.html
> +      <div class="column">
Blank column; remove.

2024-04-10 17:27 UTC, askmeaboutlo0m commented on _includes/footer.html
> +      </div><div style="display: flex; flex-direction: column; justify-content: center; row-gap: 1rem;" class="column is-narrow">
Don't interfere with Bulma's layout like this without a good reason. Laying out some text is not a good reason. Also don't use `style`, put extra styling into `_sass/main.scss` instead.

2024-04-10 17:27 UTC, askmeaboutlo0m commented on _includes/footer.html
> +        <a href="/devblog/" target="_blank"><span class="icon"><i class="fa fa-code"></i></span> Dev Blog</a><br>
It's called "development blog" everywhere else, so this change is inconsistent.

2024-04-11 05:58 UTC, MorrowShore commented
Were more or less testing the waters with new process on a single file. 
Pull request will be closed as there will be a comprehensive overhaul soon.

2024-04-11 05:58 UTC, closed without merging